'use strict';
const T = require('./testenv');
const M = require('../js/club-media');
const Engine = require('../js/engine');
const path = require('path');
(async () => {
  const { chk, done } = T.makeRunner('club-media-server');
  const { players, gws } = T.genTestData();
  const server = await T.serveTestData(path.join(__dirname, 'fixtures/testdata'));
  await T.wipe();
  const league = 'the-league-2627', base = `v2/leagues/${league}`;
  const members = await T.provision(league, [{ managerId: 1, email: 'one@test.local', role: 'commissioner' }, { managerId: 2, email: 'two@test.local' }]);
  const one = await T.idTokenFor(members[1].uid), two = await T.idTokenFor(members[2].uid);
  const db = T.initAdmin().database();
  const seed = T.buildSeedState(players);
  seed.pressers = { 1: { '0:pre': { t: 10, answers: [{ tone: 'confident', text: 'We will win.' }] } }, 2: { '0:pre': { t: 10, answers: [{ tone: 'unhinged', text: 'Never in doubt.' }] } } };
  const eng = Engine.make({ players, gameweeks: gws.map(g => ({ ...g, from: g.deadline })), now: () => Date.now() });
  const gw = eng.currentGwIndex();
  await db.ref(`${base}/public`).set(seed);
  const item = M.incident({ ...seed, matchStats: {} }, 1, gw, eng), item2 = M.incident({ ...seed, matchStats: {} }, 2, gw, eng);
  const payload = { gw, key: item.key, choice: 'ban' };
  chk('unauthenticated response rejected', (await T.mutate(league, 'mediaRespond', payload, null)).error?.status === 'UNAUTHENTICATED');
  chk('another manager cannot answer this case', !!(await T.mutate(league, 'mediaRespond', { ...payload, asManager: 1 }, two)).error);
  chk('past and future rounds rejected', !!(await T.mutate(league, 'mediaRespond', { ...payload, gw: gw - 1 }, one)).error && !!(await T.mutate(league, 'mediaRespond', { ...payload, gw: gw + 1 }, one)).error);
  chk('fabricated story rejected', !!(await T.mutate(league, 'mediaRespond', { ...payload, key: 'made-up' }, one)).error);
  chk('unoffered response rejected', !!(await T.mutate(league, 'mediaRespond', { ...payload, choice: 'blame' }, one)).error);
  const races = await Promise.all(['ban', 'double'].map(choice => T.mutate(league, 'mediaRespond', { ...payload, choice }, one)));
  chk('two conflicting responses commit exactly once', races.filter(r => r.result?.ok).length === 1 && races.filter(r => r.error).length === 1, JSON.stringify(races));
  const stored = (await db.ref(`${base}/public/mediaCases/1/${gw}`).get()).val();
  chk('server stores the offered statement and consequence', stored && stored.line === M.OPTIONS[stored.choice].line && stored.report && stored.speaker);
  const otherRead = await T.rest('GET', `${base}/public/mediaCases/1/${gw}`, { token: two });
  chk('another device receives exactly the same public story', otherRead.status === 200 && JSON.stringify(otherRead.val) === JSON.stringify(stored));
  const retry = await T.mutate(league, 'mediaRespond', { ...payload, choice: stored.choice }, one);
  chk('retry is idempotent, including original time', retry.result?.record?.t === stored.t);
  const before = (await db.ref(`${base}/public`).get()).val();
  const response2 = await T.mutate(league, 'mediaRespond', { gw, key: item2.key, choice: 'ban', asManager: 1 }, two);
  chk('actor is token owner even with an asManager override', response2.result?.ok && (await db.ref(`${base}/public/mediaCases/2/${gw}`).get()).exists());
  const after = (await db.ref(`${base}/public`).get()).val();
  delete before.mediaCases; delete after.mediaCases;
  chk('no game state changed', JSON.stringify(before) === JSON.stringify(after));
  chk('direct client writes denied', (await T.rest('PUT', `${base}/public/mediaCases/1/${gw}`, { token: one, body: { choice: 'fake' } })).status !== 200);
  const exported = (await db.ref(`${base}/public`).get()).val();
  const imported = await T.mutate(league, 'importState', { state: exported }, one);
  chk('real RTDB array-shaped cases survive backup import', imported.result?.ok, JSON.stringify(imported));
  chk('saved response survives import exactly', JSON.stringify((await db.ref(`${base}/public/mediaCases/1/${gw}`).get()).val()) === JSON.stringify(stored));
  const bad = structuredClone(exported); bad.mediaCases[1][gw].choice = '__proto__';
  chk('malformed imported choice rejected', !!(await T.mutate(league, 'importState', { state: bad }, one)).error);
  await db.ref(`${base}/public/mediaCases`).remove();
  await db.ref(`${base}/public/pressers/1/0:pre/answers/0/text`).set('The story changed.');
  chk('stale browser story cannot be filed after evidence changes', !!(await T.mutate(league, 'mediaRespond', payload, one)).error);
  await new Promise(resolve => server.close(resolve));
  done();
})().catch(e => { console.error(e); process.exit(1); });
